### ISSUE TITLE
crash with small instances?

### ISSUE THREAD

**Issue by fvella** [Adam27X/hybrid_BC#1]
Hi,
I am testing your code with small hand-written instances but the executable crash.

Can you provide small instances (max 16 nodes) ?

Best,
Flavio

**Comment by Adam27X** [comment]
Hi Flavio,

Can you provide more details regarding the nature of the crash? What error message(s) do you receive? How are you running the program and with what input are you running it with?

I'll add some small test graphs that I used in testing to this repository shortly. The tests can be run as follows:

$ ./bc -i ./graphs/tiny/test1.graph -v

Which provides the following output on my system:

Chosen Device: GeForce GTX TITAN
Compute Capability: 3.5
Number of Streaming Multiprocessors: 14
Size of Global Memory: 5.99969 GB

Number of nodes: 9
Number of edges: 8
RMS Error: 0
Maximum error: 0
Time for CPU Algorithm: 1.55840007e-05 s
Time for GPU Algorithm: 0.00128815998 s

Hope this helps.

Best,

Adam

**Comment by fvella** [comment]
Hi Adam,
thanks for your reply.
Here's the details

 ./bc -i small.graph -v
Chosen Device: Tesla K20c
Compute Capability: 3.5
Number of Streaming Multiprocessors: 13
Size of Global Memory: 4.68707 GB

**\* glibc detected **\* ./bc: malloc(): memory corruption (fast): 0x000000000252f800 ***
======= Backtrace: =========
/lib64/libc.so.6[0x35e4a75e66]
/lib64/libc.so.6[0x35e4a79c3f]
/lib64/libc.so.6(__libc_malloc+0x71)[0x35e4a7a6b1]
/usr/lib64/libstdc++.so.6(_Znwm+0x1d)[0x35f06bd0bd]
./bc[0x40db46]
./bc[0x40ef7e]
./bc[0x409ab5]
./bc[0x40bc0b]
./bc[0x4053c5]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x35e4a1ed5d]
./bc[0x404089]
======= Memory map: ========
00400000-00468000 r-xp 00000000 fd:02 4326769                            /home/fvella/Downloads/hybrid_BC-master/bc
00668000-0066b000 rw-p 00068000 fd:02 4326769                            /home/fvella/Downloads/hybrid_BC-master/bc

The problem occurs during the parsing, I guess.
Probably the instance which I use is not well formatted.

======= small graph =========

0 1
1 2
1 3
1 6
3 4
3 5
5 2
5 6
6 8
7 8
8 9

# 

Best,
Flavio

**Comment by Adam27X** [comment]
Ah, yes. For graphs that are represented as edgelists the program expects the file extension to be ".txt" or ".edge" whereas the ".graph" extension is reserved for graphs in metis (DIMACS) format. 

Changing the name from "small.graph" to "small.txt" should work.

If I get the time I can improve the command line arguments such that the user specifies the format rather than assuming a format based on the extension of the file. Thanks for bringing this up.

Best,

Adam

**Comment by fvella** [comment]
Thanks Adam!
Best,
Flavio
